### PR TITLE
Short pdf report extension for quarto

### PR DESCRIPTION
**Pull request by VMT1312**

### CODE REVIEW

**Review by adamhsparks — CHANGES_REQUESTED** [review]
There is already a template-short-report.qmd, there's no reason to have the template-pdf (which isn't clearly named in line with the template as well). Please remove this and align the example with the template name.

**Comment by VMT1312** [comment]
that's one should be the template-pdf-report.qmd to align with the makefile. I will change it from "template-pdf.qmd" to "template-pdf-report.qmd".

**Comment by VMT1312** [comment]
And I tried to use the template to create sample demos, I found that it doesn't render with docx-report but with docx+report (similar to pdf+lor in the Stanford extension). Do you want me to make that change as well?

**Comment by adamhsparks** [comment]
Thanks, I'm having my own issues understanding what GitHub is showing me in the changes that you've made. It looks as if you added "pdf-report.qmd" in this PR. Weird.

**Review by adamhsparks — APPROVED** [review]

**Comment by adamhsparks** [comment]
@VMT1312, have you tested all of the templates to see if the extension works? With the last PR I had to fix a few things before they worked.

**Comment by VMT1312** [comment]
I'm not sure why aagi-docx-report didn't work for me but change to aagi-docx+report works for me

**Comment by adamhsparks** [comment]
> I'm not sure why aagi-docx-report didn't work for me but change to aagi-docx+report works for me

I'm guessing it's file path or just file name issues at play here. See if you can get it work with the "-" not "+", please. The revealjs works with the "-" in the name for me.

**Comment by VMT1312** [comment]
> > I'm not sure why aagi-docx-report didn't work for me but change to aagi-docx+report works for me
> 
> I'm guessing it's file path or just file name issues at play here. See if you can get it work with the "-" not "+", please. The revealjs works with the "-" in the name for me.

After digging around on the web (nothing much) and trial-and-error, I think that with "aagi-revealjs-a", quarto tries to look for the extension "aagi-revealjs" (ERROR: Unable to read the extension "aagi-revealjs".).

On the other hand, with "aagi-revealjs+a", it understand only "aagi" as the extension name and the rest is the custom output format.

The stanford "pdf+lor" is the only example I could find (it spitted out the same error when I changed to "pdf-lor"), all other custom formats that listed under the quarto website follow "custom name-output"

**Comment by adamhsparks** [comment]
Nice work! Go with the "+" in that case

**Pull request merged**
