### PR TITLE
Remove the csl option in the extension so the biometric.csl is not needed and add in the _quarto.yml file to be able to publish

### PR DESCRIPTION
**Pull request by VMT1312**

### CODE REVIEW

**Comment by adamhsparks** [comment]
shouldn't we use a standard CSL across the AAGI packages rather than just removing it completely?

**Comment by VMT1312** [comment]
Because the biometrics.csl was copied from the short report pdf from the rmarkdown template, I'm not sure if you want to use it for every document or not, that's why I took it out

**Comment by VMT1312** [comment]
The biometrics.csl is saved in the docs\demos so if you want it for both the pdf-report and short-pdf-report, I will save another copy in the assets folder

**Comment by adamhsparks** [comment]
I'd like us to have a standard format for references in AAGI, this is a good way to ensure that if we can ship it in the Quarto extension for both report and Revealjs formats

**Pull request merged**
