### PR TITLE
Add in the word and pdf output

### PR DESCRIPTION
**Pull request by VMT1312**
Update with three outputs and try to mimic the folder structure similar to Stanford:

- There are three folders sitting under the extension folder for each output
- Add in a demos folder to generate example document using the defined template
- Add in a template.qmd file to be used as the report generator (the name will change accordingly when install the template)

### CODE REVIEW

**Comment by adamhsparks** [comment]
Hi Vinh, can you please add yourself to the author list of this template?

**Comment by adamhsparks** [comment]
Also, please note that the structure of this should have templates for the individual outputs in the respective `docs` folder, refer to https://github.com/coatless-quarto/stanford/blob/a35eb826abe9fb97c20dfd27d3699154546b87cd/docs/demos/template-revealjs.qmd

**Comment by VMT1312** [comment]
To my understanding, you want three separate folders for each output in the demos folder as well?

**Comment by adamhsparks** [comment]
@VMT1312, I think I've fixed any of the issues with generating a PDF. We were missing the resource files, _e.g._, AAGI_logo.pdf, etc.

**Review by adamhsparks — APPROVED** [review]

**Pull request merged**
